Add e2fsprogs to build dependencies (for tests)
This is a test dependency, needed to fix:

  ERROR: test/update_handler
  ERROR: test/install

Signed-off-by: Arnaud Rebillout <arnaud.rebillout@collabora.com>